import Task from '../models/Task';
import Meeting from '../models/Meeting';
import type { ITask } from '../types/index';

export class TaskService {
  static async createTask(userId: string, taskData: Partial<ITask>): Promise<ITask> {
    const task = await Task.create({ ...taskData, userId });
    return task;
  }

  static async upsertPendingFollowUp(userId: string, taskData: Partial<ITask>): Promise<ITask> {
    const metadata = (taskData.metadata ?? {}) as Record<string, unknown>;
    const purpose = String(metadata.followUpPurpose ?? 'general_follow_up').slice(0, 80);
    const globalTaskKey = metadata.contactId ? `${String(metadata.contactId)}:${purpose}` : undefined;
    const metadataSet = Object.fromEntries(Object.entries({ ...metadata, ...(globalTaskKey ? { globalTaskKey } : {}) }).filter(([key]) => !['origins', 'sourceEventIds'].includes(key)).map(([key, value]) => [`metadata.${key}`, value]));
    const origins = [...new Set((Array.isArray(metadata.origins) ? metadata.origins : []).map(String).filter(Boolean))];
    const sourceEventIds = [...new Set((Array.isArray(metadata.sourceEventIds) ? metadata.sourceEventIds : metadata.sourceEventId ? [metadata.sourceEventId] : []).map(String).filter(Boolean))];
    const contactScope = metadata.contactId ? { 'metadata.contactId': String(metadata.contactId) } : { leadId: taskData.leadId, conversationId: taskData.conversationId };
    const purposeFilter = purpose === 'assisted_conversation_review'
      ? { $or: [{ 'metadata.followUpPurpose': purpose }, { 'metadata.followUpPurpose': { $exists: false }, 'metadata.suggestedOnly': true }] }
      : purpose === 'general_follow_up'
        ? { $or: [{ 'metadata.followUpPurpose': purpose }, { 'metadata.followUpPurpose': { $exists: false }, 'metadata.autoGenerated': true }] }
        : { 'metadata.followUpPurpose': purpose };
    try { const task = await Task.findOneAndUpdate(
      { userId, ...contactScope, type: 'follow_up', status: 'pending', ...purposeFilter },
      {
        $set: { description: taskData.description, dueDate: taskData.dueDate, priority: taskData.priority, 'metadata.followUpPurpose': purpose, ...metadataSet },
        $setOnInsert: { userId, leadId: taskData.leadId, conversationId: taskData.conversationId, title: taskData.title || 'Hacer seguimiento al prospecto', type: 'follow_up', status: 'pending' },
        ...(origins.length || sourceEventIds.length ? { $addToSet: { ...(origins.length ? { 'metadata.origins': { $each: origins } } : {}), ...(sourceEventIds.length ? { 'metadata.sourceEventIds': { $each: sourceEventIds } } : {}) } } : {}),
      },
      { upsert: true, new: true },
    );
    return task;
    } catch (error: any) {
      if (error?.code !== 11000 || !globalTaskKey) throw error;
      const winner = await Task.findOne({ userId, status: 'pending', 'metadata.globalTaskKey': globalTaskKey });
      if (!winner) throw error;
      return winner;
    }
  }

  static async getUserTasks(userId: string): Promise<ITask[]> {
    await this.reconcileMeetingTasks(userId);
    return await Task.find({ userId }).sort({ dueDate: 1, createdAt: -1 });
  }

  static async reconcileMeetingTasks(userId: string, now = new Date()): Promise<void> {
    const tasks: any[] = await Task.find({ userId, type: 'meeting', status: 'pending', 'metadata.autoGenerated': true, 'metadata.meetingId': { $exists: true } })
      .select('_id dueDate metadata').lean();
    if (!tasks.length) return;
    const meetingIds = [...new Set(tasks.map(task => task.metadata?.meetingId).filter(Boolean))];
    const meetings: any[] = await Meeting.find({ _id: { $in: meetingIds }, userId }).select('_id status scheduledFor').lean();
    const byId = new Map(meetings.map(meeting => [meeting._id.toString(), meeting]));
    const completed: any[] = [];
    const cancelled: any[] = [];
    for (const task of tasks) {
      const meeting = byId.get(String(task.metadata?.meetingId));
      if (!meeting) continue;
      if (meeting.status === 'cancelled') cancelled.push(task._id);
      else if (meeting.status === 'scheduled' && meeting.scheduledFor && new Date(meeting.scheduledFor) <= now) completed.push(task._id);
      else if (meeting.status === 'pending_configuration' && task.dueDate && new Date(task.dueDate) <= now) cancelled.push(task._id);
    }
    await Promise.all([
      completed.length ? Task.updateMany({ _id: { $in: completed } }, { $set: { status: 'completed' } }) : Promise.resolve(),
      cancelled.length ? Task.updateMany({ _id: { $in: cancelled } }, { $set: { status: 'cancelled' } }) : Promise.resolve(),
    ]);
  }

  static async getTaskById(taskId: string, userId: string): Promise<ITask | null> {
    return await Task.findOne({ _id: taskId, userId });
  }

  static async updateTask(taskId: string, userId: string, updateData: Partial<ITask>): Promise<ITask | null> {
    return await Task.findOneAndUpdate({ _id: taskId, userId }, updateData, { new: true });
  }

  static async deleteTask(taskId: string, userId: string): Promise<boolean> {
    const result = await Task.deleteOne({ _id: taskId, userId });
    return result.deletedCount > 0;
  }
}
