import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import Launch from '../src/models/Launch'; import LaunchSegmentVersion from '../src/models/LaunchSegmentVersion'; import LaunchParticipant from '../src/models/LaunchParticipant'; import LaunchEvent from '../src/models/LaunchEvent';
import Lead from '../src/models/Lead'; import Meeting from '../src/models/Meeting'; import ContactProfile from '../src/models/ContactProfile'; import ContactIdentity from '../src/models/ContactIdentity'; import DuplicateCandidate from '../src/models/DuplicateCandidate'; import OutboundMessage from '../src/models/OutboundMessage';
import { LaunchLifecycleService } from '../src/services/LaunchLifecycleService'; import { LaunchSegmentationService } from '../src/services/LaunchSegmentationService';
import type { TargetSegmentDefinition } from '../src/types/launch';

describe('Launch L2 assisted segmentation', () => {
  let mongo: MongoMemoryServer; const now = new Date('2027-08-01T12:00:00Z');
  beforeAll(async () => { mongo = await MongoMemoryServer.create(); await mongoose.connect(mongo.getUri()); await Promise.all([Launch.syncIndexes(), LaunchSegmentVersion.syncIndexes(), LaunchParticipant.syncIndexes(), LaunchEvent.syncIndexes()]); });
  afterEach(async () => { await Promise.all([Launch.deleteMany({}), LaunchSegmentVersion.deleteMany({}), LaunchParticipant.deleteMany({}), LaunchEvent.deleteMany({}), Lead.deleteMany({}), Meeting.deleteMany({}), ContactProfile.deleteMany({}), ContactIdentity.deleteMany({}), DuplicateCandidate.deleteMany({}), OutboundMessage.deleteMany({})]); });
  afterAll(async () => { await mongoose.disconnect(); await mongo.stop(); });
  const segment = (rules: any[], logic: 'AND' | 'OR' = 'AND', groups: any[] = []): TargetSegmentDefinition => ({ schemaVersion: 1, logic, rules, groups });
  const launch = (userId: any, key = new mongoose.Types.ObjectId().toString()) => LaunchLifecycleService.createLaunch(userId.toString(), { name: 'L2', timezone: 'America/Bogota', startsAt: now, eventStartsAt: new Date(now.getTime() + 86400000), closesAt: new Date(now.getTime() + 172800000), allowedChannels: ['whatsapp', 'instagram', 'manual'], idempotencyKey: key, actor: 'owner' });
  const lead = (userId: any, suffix: string, extra: any = {}) => Lead.create({ userId, username: suffix, platform: 'whatsapp', currentChannel: 'whatsapp', status: 'interested', interestLevel: 'warm', score: 70, lastContact: new Date(now.getTime() - 86400000), tags: ['ventas'], normalizedIntent: 'business_interest', normalizedIntents: ['business_interest'], ...extra });

  test('validates a versioned closed contract and rejects arbitrary/deep rules', () => {
    expect(LaunchSegmentationService.validate(segment([{ id: 'score', field: 'score', operator: 'gte', value: 60 }]))).toMatchObject({ schemaVersion: 1 });
    expect(() => LaunchSegmentationService.validate(segment([{ id: 'unsafe', field: '$where', operator: 'eq', value: true }]))).toThrow(/Regla/);
    expect(() => LaunchSegmentationService.validate({ schemaVersion: 1, logic: 'AND', rules: [], groups: [] })).toThrow(/entre 1 y 30/);
  });

  test('evaluates simple score and returns structured reasons', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); await lead(userId, 'high'); await lead(userId, 'low', { score: 30 }); const snapshot: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'score60', field: 'score', operator: 'gte', value: 60 }]), 'owner'); const preview: any = await LaunchSegmentationService.preview(userId.toString(), item._id.toString(), { version: snapshot.version, limit: 10, now });
    expect(preview).toMatchObject({ totalEvaluated: 2, eligible: 1, notEligible: 1 }); expect(preview.results.flatMap((entry: any) => entry.reasons)).toEqual(expect.arrayContaining([expect.objectContaining({ ruleId: 'score60', code: 'criterion_matched' }), expect.objectContaining({ ruleId: 'score60', code: 'criterion_not_matched' })]));
  });

  test('supports AND, OR and bounded nested groups', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const candidate: any = await lead(userId, 'candidate'); const definition = segment([{ id: 'hot', field: 'interest_level', operator: 'eq', value: 'hot' }], 'OR', [{ id: 'group', logic: 'AND', rules: [{ id: 'score', field: 'score', operator: 'gte', value: 60 }, { id: 'tag', field: 'tags', operator: 'contains', value: 'ventas' }] }]); const result = await LaunchSegmentationService.evaluate(userId.toString(), item, [candidate.toObject()], definition, now); expect(result[0]).toMatchObject({ eligible: true, criteriaMatched: true });
  });

  test('uses temperature, intent history, tags, channel and recent activity without AI', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const candidate: any = await lead(userId, 'signals'); const definition = segment([{ id: 'temp', field: 'interest_level', operator: 'eq', value: 'warm' }, { id: 'intent', field: 'intent_history', operator: 'contains', value: 'business_interest' }, { id: 'tag', field: 'tags', operator: 'contains', value: 'ventas' }, { id: 'channel', field: 'channel', operator: 'eq', value: 'whatsapp' }, { id: 'recent', field: 'recent_activity_days', operator: 'lte', value: 3 }]); const result = await LaunchSegmentationService.evaluate(userId.toString(), item, [candidate.toObject()], definition, now); expect(result[0].eligible).toBe(true); expect(result[0].reasons).toHaveLength(5);
  });

  test('safety excludes terminal status, active meeting and opt-out regardless of matching rules', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const rejected: any = await lead(userId, 'rejected', { status: 'rejected' }); const meetingLead: any = await lead(userId, 'meeting'); const opted: any = await lead(userId, 'opted'); await Meeting.create({ userId, leadId: meetingLead._id, status: 'confirmed', scheduledFor: new Date(now.getTime() + 86400000) }); const contact: any = await ContactProfile.create({ userId, createdBy: 'owner', generalOptOut: true }); await ContactIdentity.create({ userId, contactId: contact._id, leadId: opted._id, platform: 'whatsapp', externalId: 'opted', confirmationSource: 'human' }); const definition = segment([{ id: 'all', field: 'score', operator: 'gte', value: 0 }]); const results = await LaunchSegmentationService.evaluate(userId.toString(), item, [rejected.toObject(), meetingLead.toObject(), opted.toObject()], definition, now); expect(results.every(entry => !entry.eligible && entry.safetyBlocked)).toBe(true); expect(results.flatMap(entry => entry.reasons.map(reason => reason.code))).toEqual(expect.arrayContaining(['terminal_status', 'active_meeting', 'general_opt_out']));
  });

  test('preview is paginated, provides distributions and never creates participants', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); await lead(userId, 'one'); await lead(userId, 'two', { interestLevel: 'hot', currentChannel: 'instagram', platform: 'instagram' }); const saved: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'all', field: 'score', operator: 'gte', value: 0 }]), 'owner'); const preview: any = await LaunchSegmentationService.preview(userId.toString(), item._id.toString(), { version: saved.version, page: 1, limit: 1, now, actor: 'owner', idempotencyKey: 'preview-1' }); expect(preview).toMatchObject({ totalAvailable: 2, totalEvaluated: 1, page: 1, limit: 1 }); expect(await LaunchParticipant.countDocuments()).toBe(0); expect(await LaunchEvent.findOne({ eventType: 'launch.segment_previewed' })).not.toBeNull();
  });

  test('segment versions and selection snapshots remain immutable after later changes', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const candidate: any = await lead(userId, 'snapshot'); const v1: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'score60', field: 'score', operator: 'gte', value: 60 }]), 'owner'); await LaunchSegmentationService.confirmSelection(userId.toString(), item._id.toString(), { segmentVersion: 1, decisions: [{ leadId: candidate._id.toString(), selected: true }], idempotencyKey: 'select-v1', actor: 'owner' }); const v2: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'score90', field: 'score', operator: 'gte', value: 90 }]), 'owner'); const participant: any = await LaunchParticipant.findOne({ leadId: candidate._id }); expect(v1.version).toBe(1); expect(v2.version).toBe(2); expect(participant.metadata.selection).toMatchObject({ segmentVersion: 1, definitionHash: v1.definitionHash }); expect((await LaunchSegmentVersion.findOne({ version: 1 }))?.definition).toMatchObject({ rules: [expect.objectContaining({ id: 'score60' })] });
  });

  test('human selection, exclusion and permitted override are audited', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const eligible: any = await lead(userId, 'eligible'); const excluded: any = await lead(userId, 'excluded', { score: 20 }); const saved: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'score60', field: 'score', operator: 'gte', value: 60 }]), 'owner'); await LaunchSegmentationService.confirmSelection(userId.toString(), item._id.toString(), { segmentVersion: saved.version, decisions: [{ leadId: eligible._id.toString(), selected: false, overrideReason: 'No corresponde ahora' }, { leadId: excluded._id.toString(), selected: true, overrideReason: 'Conocimiento directo documentado' }], idempotencyKey: 'human-decisions', actor: 'owner' }); expect(await LaunchParticipant.countDocuments({ launchId: item._id })).toBe(1); expect(await LaunchEvent.findOne({ eventType: 'launch.segment_selection_excluded' })).not.toBeNull(); expect(await LaunchEvent.findOne({ eventType: 'launch.segment_selection_overridden' })).not.toBeNull();
  });

  test('human override cannot bypass a safety exclusion', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const blocked: any = await lead(userId, 'blocked', { status: 'rejected' }); const saved: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'all', field: 'score', operator: 'gte', value: 0 }]), 'owner'); await expect(LaunchSegmentationService.confirmSelection(userId.toString(), item._id.toString(), { segmentVersion: saved.version, decisions: [{ leadId: blocked._id.toString(), selected: true, overrideReason: 'Intento' }], idempotencyKey: 'unsafe', actor: 'owner' })).rejects.toMatchObject({ code: 'SAFETY_OVERRIDE_FORBIDDEN' });
  });

  test('manual direct selection is distinct, idempotent and owner-scoped', async () => {
    const userId = new mongoose.Types.ObjectId(), other = new mongoose.Types.ObjectId(), item: any = await launch(userId); const candidate: any = await lead(userId, 'manual'); const [one, two]: any[] = await Promise.all([LaunchSegmentationService.addManual(userId.toString(), item._id.toString(), { leadId: candidate._id.toString(), reason: 'Selección directa', idempotencyKey: 'manual-one', actor: 'owner' }), LaunchSegmentationService.addManual(userId.toString(), item._id.toString(), { leadId: candidate._id.toString(), reason: 'Selección directa', idempotencyKey: 'manual-one', actor: 'owner' })]); expect(one._id.toString()).toBe(two._id.toString()); expect(await LaunchParticipant.countDocuments()).toBe(1); await expect(LaunchSegmentationService.addManual(other.toString(), item._id.toString(), { leadId: candidate._id.toString(), reason: 'Ajeno', idempotencyKey: 'other', actor: 'other' })).rejects.toMatchObject({ code: 'LAUNCH_NOT_FOUND' });
  });

  test('same lead can be selected in another launch while duplicates in one launch stay idempotent', async () => {
    const userId = new mongoose.Types.ObjectId(), first: any = await launch(userId, 'first'), second: any = await launch(userId, 'second'), candidate: any = await lead(userId, 'repeat'); await LaunchSegmentationService.addManual(userId.toString(), first._id.toString(), { leadId: candidate._id.toString(), reason: 'Primero', idempotencyKey: 'first-add', actor: 'owner' }); await LaunchSegmentationService.addManual(userId.toString(), second._id.toString(), { leadId: candidate._id.toString(), reason: 'Segundo', idempotencyKey: 'second-add', actor: 'owner' }); expect(await LaunchParticipant.countDocuments({ leadId: candidate._id })).toBe(2);
  });

  test('possible duplicate is only warned and never auto-merged', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const one: any = await lead(userId, 'dup-a'), two: any = await lead(userId, 'dup-b'); await DuplicateCandidate.create({ userId, leadAId: one._id, leadBId: two._id, candidateKey: 'candidate', signals: ['email'] }); const definition = segment([{ id: 'all', field: 'score', operator: 'gte', value: 0 }]); const result = await LaunchSegmentationService.evaluate(userId.toString(), item, [one.toObject(), two.toObject()], definition, now); expect(result.every(entry => entry.possibleDuplicateCandidateIds.length === 1)).toBe(true); expect(await ContactIdentity.countDocuments()).toBe(0);
  });

  test('all L2 operations keep OutboundMessage at zero', async () => {
    const userId = new mongoose.Types.ObjectId(), item: any = await launch(userId); const candidate: any = await lead(userId, 'safe'); const saved: any = await LaunchSegmentationService.save(userId.toString(), item._id.toString(), segment([{ id: 'all', field: 'score', operator: 'gte', value: 0 }]), 'owner'); await LaunchSegmentationService.preview(userId.toString(), item._id.toString(), { version: saved.version, now }); await LaunchSegmentationService.confirmSelection(userId.toString(), item._id.toString(), { segmentVersion: saved.version, decisions: [{ leadId: candidate._id.toString(), selected: true }], idempotencyKey: 'safe-select', actor: 'owner' }); expect(await OutboundMessage.countDocuments()).toBe(0);
  });
});
