import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import Meeting from '../src/models/Meeting';
import Lead from '../src/models/Lead';
import Conversation from '../src/models/Conversation';
import Task from '../src/models/Task';
import AutomationFlow from '../src/models/AutomationFlow';
import AutomationExecution from '../src/models/AutomationExecution';
import { MeetingLifecycleService } from '../src/services/MeetingLifecycleService';
import { MeetingAvailabilityService } from '../src/services/MeetingAvailabilityService';
import type { MeetingProvider, MeetingRequest, MeetingResult } from '../src/integrations/meetings';
import { MeetingProviderError } from '../src/integrations/meetings';

class Provider implements MeetingProvider {
  name = 'test'; createCalls = 0; updateCalls = 0; cancelCalls = 0; fail = false;
  async createMeeting(request: MeetingRequest): Promise<MeetingResult> { this.createCalls++; if (this.fail) throw new MeetingProviderError('Zoom rechazó', 'ZOOM_TEST_ERROR'); return { externalId: 'zoom-1', joinUrl: 'https://zoom.us/j/1', startUrl: 'https://zoom.us/s/secret', scheduledFor: request.scheduledFor, simulated: false }; }
  async updateMeeting(externalId: string, request: MeetingRequest) { this.updateCalls++; return { externalId, joinUrl: '', scheduledFor: request.scheduledFor, simulated: false }; }
  async cancelMeeting() { this.cancelCalls++; }
}

describe('Phase 7 confirmed meeting lifecycle', () => {
  let mongo: MongoMemoryServer; let ownerA: string; let ownerB: string; let lead: any; let conversation: any; let context: any; const originalEnv = process.env;
  beforeAll(async () => { mongo = await MongoMemoryServer.create(); await mongoose.connect(mongo.getUri()); });
  beforeEach(async () => { process.env = { ...originalEnv, MEETING_AVAILABLE_DAYS: '0,1,2,3,4,5,6', MEETING_START_TIME: '09:00', MEETING_END_TIME: '12:00', MEETING_DURATION_MINUTES: '30', MEETING_TIMEZONE: 'America/Bogota', MEETING_HORIZON_DAYS: '30', MEETING_MAX_OPTIONS: '3' }; ownerA = new mongoose.Types.ObjectId().toString(); ownerB = new mongoose.Types.ObjectId().toString(); lead = await Lead.create({ userId: ownerA, username: 'meeting-lead', platform: 'whatsapp' }); conversation = await Conversation.create({ userId: ownerA, leadId: lead._id }); context = { userId: ownerA, leadId: lead._id.toString(), conversationId: conversation._id.toString(), sourceEventId: 'source-meeting-1', platform: 'whatsapp', timezone: 'America/Bogota', attendeeEmail: 'lead@example.com' }; });
  afterEach(async () => { process.env = originalEnv; await Promise.all([Meeting.deleteMany({}), Lead.deleteMany({}), Conversation.deleteMany({}), Task.deleteMany({}), AutomationFlow.deleteMany({}), AutomationExecution.deleteMany({})]); });
  afterAll(async () => { await mongoose.disconnect(); await mongo.stop(); });
  const selected = async (service: MeetingLifecycleService) => { await service.propose(context); return service.select(context, 1); };

  test('distinguishes low from sufficient conversational meeting intent', () => { expect(MeetingLifecycleService.hasSufficientIntent('Tal vez algún día una reunión')).toBe(false); expect(MeetingLifecycleService.isLowIntent('Tal vez algún día una reunión')).toBe(true); expect(MeetingLifecycleService.hasSufficientIntent('Quiero agendar una reunión')).toBe(true); });
  test('proposes availability without creating Zoom', async () => { const provider = new Provider(); const outcome = await new MeetingLifecycleService(provider).propose(context); expect(outcome.meeting).toMatchObject({ status: 'pending_confirmation', provider: 'zoom' }); expect(outcome.meeting.proposedSlots).toHaveLength(3); expect(provider.createCalls).toBe(0); });
  test('records a selection and asks for explicit confirmation', async () => { const service = new MeetingLifecycleService(new Provider()); const outcome = await selected(service); expect(outcome.meeting.selectedSlot).toBeTruthy(); expect(outcome.reply).toContain('confirmo'); });
  test('creates official Zoom only after confirmation', async () => { const provider = new Provider(); const service = new MeetingLifecycleService(provider); await selected(service); const outcome = await service.confirm(context); expect(provider.createCalls).toBe(1); expect(outcome.meeting).toMatchObject({ status: 'confirmed', externalMeetingId: 'zoom-1', joinUrl: 'https://zoom.us/j/1' }); });
  test('prevents two concurrent confirmations from creating two meetings', async () => { const provider = new Provider(); const service = new MeetingLifecycleService(provider); await selected(service); await Promise.all([service.confirm(context), service.confirm(context)]); expect(provider.createCalls).toBe(1); expect(await Meeting.countDocuments({ conversationId: conversation._id })).toBe(1); });
  test('keeps mock success pending configuration rather than falsely confirmed', async () => { const provider: MeetingProvider = { name: 'mock', createMeeting: async request => ({ externalId: 'mock-1', joinUrl: 'https://zoom.mock.invalid/1', simulated: true, scheduledFor: request.scheduledFor }) }; const service = new MeetingLifecycleService(provider); await selected(service); expect((await service.confirm(context)).meeting.status).toBe('pending_configuration'); });
  test('persists Zoom failure and supports a safe retry', async () => { const provider = new Provider(); provider.fail = true; const service = new MeetingLifecycleService(provider); await selected(service); expect((await service.confirm(context)).meeting).toMatchObject({ status: 'failed', errorCode: 'ZOOM_TEST_ERROR' }); provider.fail = false; expect((await service.confirm(context)).meeting.status).toBe('confirmed'); expect(provider.createCalls).toBe(2); });
  test('does not expose protected startUrl in normal CRM queries', async () => { const provider = new Provider(); const service = new MeetingLifecycleService(provider); await selected(service); const confirmed = await service.confirm(context); expect(confirmed.meeting.startUrl).toContain('/secret'); expect((await Meeting.findById(confirmed.meeting._id) as any).startUrl).toBeUndefined(); });
  test('cancels in Zoom and CRM under the same owner', async () => { const provider = new Provider(); const service = new MeetingLifecycleService(provider); await selected(service); const confirmed = await service.confirm(context); expect(await service.cancel(ownerB, confirmed.meeting._id.toString())).toBeNull(); expect((await service.cancel(ownerA, confirmed.meeting._id.toString()))?.status).toBe('cancelled'); expect(provider.cancelCalls).toBe(1); });
  test('prepares and confirms official rescheduling', async () => { const provider = new Provider(); const service = new MeetingLifecycleService(provider); await selected(service); await service.confirm(context); const proposal = await service.requestReschedule(context); expect(proposal.meeting.status).toBe('reschedule_requested'); await service.select(context, 2); const updated = await service.confirm(context); expect(updated.meeting.status).toBe('confirmed'); expect(provider.updateCalls).toBe(1); expect(provider.createCalls).toBe(1); });
  test('converts configured local timezone without double offset', () => { expect(MeetingAvailabilityService.toUtc('2027-08-20', '10:00', 'America/Bogota')?.toISOString()).toBe('2027-08-20T15:00:00.000Z'); });
  test('reserves a selected slot against another confirmed meeting', async () => { const slot = new Date('2027-08-20T15:00:00.000Z'); await Meeting.create({ userId: ownerA, leadId: lead._id, conversationId: conversation._id, status: 'confirmed', scheduledAt: slot, durationMinutes: 30 }); expect(await MeetingAvailabilityService.isAvailable(ownerA, slot, 30)).toBe(false); expect(await MeetingAvailabilityService.isAvailable(ownerB, slot, 30)).toBe(true); });
  test('emits meeting.confirmed into the automation engine', async () => { await AutomationFlow.create({ userId: ownerA, name: 'Evento reunión', status: 'active', isActive: true, trigger: { type: 'meeting.confirmed' }, actions: [{ type: 'add_tag', config: { tag: 'meeting-confirmed' } }] }); const service = new MeetingLifecycleService(new Provider()); await selected(service); await service.confirm(context); expect((await Lead.findById(lead._id))?.tags).toContain('meeting-confirmed'); expect(await AutomationExecution.countDocuments({ trigger: 'meeting.confirmed' })).toBe(1); });
  test('marks a confirmed meeting completed and preserves history', async () => { const service = new MeetingLifecycleService(new Provider()); await selected(service); const confirmed = await service.confirm(context); const completed: any = await service.complete(ownerA, confirmed.meeting._id.toString()); expect(completed.status).toBe('completed'); expect(completed.lifecycleHistory.at(-1).status).toBe('completed'); });
});
