import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import AutomationFlow from '../src/models/AutomationFlow';
import AutomationExecution from '../src/models/AutomationExecution';
import AutomationJob from '../src/models/AutomationJob';
import AssistedProposal from '../src/models/AssistedProposal';
import OutboundMessage from '../src/models/OutboundMessage';
import Lead from '../src/models/Lead';
import Conversation from '../src/models/Conversation';
import Task from '../src/models/Task';
import { AutomationService } from '../src/services/AutomationService';
import { AutomationEngineService, type AutomationEvent } from '../src/services/AutomationEngineService';

describe('Phase 6 automation engine', () => {
  let mongo: MongoMemoryServer; let ownerA: string; let ownerB: string; let lead: any; let conversation: any;
  beforeAll(async () => { mongo = await MongoMemoryServer.create(); await mongoose.connect(mongo.getUri()); });
  beforeEach(async () => { ownerA = new mongoose.Types.ObjectId().toString(); ownerB = new mongoose.Types.ObjectId().toString(); lead = await Lead.create({ userId: ownerA, username: 'lead-1', platform: 'whatsapp', status: 'new', tags: [] }); conversation = await Conversation.create({ userId: ownerA, leadId: lead._id }); });
  afterEach(async () => Promise.all([AutomationFlow.deleteMany({}), AutomationExecution.deleteMany({}), AutomationJob.deleteMany({}), AssistedProposal.deleteMany({}), OutboundMessage.deleteMany({}), Lead.deleteMany({}), Conversation.deleteMany({}), Task.deleteMany({})]));
  afterAll(async () => { await mongoose.disconnect(); await mongo.stop(); });

  const definition = (extra: any = {}) => ({ name: 'Regla de prueba', status: 'draft', trigger: { type: 'keyword.detected', keyword: 'INFO', keywords: ['INFO'] }, conditionLogic: 'AND', conditions: [], actions: [{ type: 'add_tag', config: { tag: 'captado' } }], ...extra });
  const event = (extra: Partial<AutomationEvent> = {}): AutomationEvent => ({ eventId: 'event-1', trigger: 'keyword.detected', userId: ownerA, leadId: lead._id.toString(), conversationId: conversation._id.toString(), platform: 'whatsapp', text: 'INFO por favor', recipient: { type: 'whatsapp_user', externalId: '+573001112233' }, data: { score: 70, interestLevel: 'warm', tags: ['nuevo'] }, ...extra });

  test('creates, edits and versions a draft', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition()); expect(flow.status).toBe('draft'); const edited: any = await AutomationService.updateFlow(flow._id, ownerA, { name: 'Regla editada' }); expect(edited).toMatchObject({ name: 'Regla editada', version: 2 }); });
  test('activates, pauses and reactivates', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition()); expect((await AutomationService.setStatus(flow._id, ownerA, 'active') as any).isActive).toBe(true); expect((await AutomationService.setStatus(flow._id, ownerA, 'paused') as any).status).toBe('paused'); expect((await AutomationService.setStatus(flow._id, ownerA, 'active') as any).status).toBe('active'); });
  test('duplicates as an inactive draft', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active' })); const copy: any = await AutomationService.duplicateFlow(flow._id, ownerA); expect(copy).toMatchObject({ status: 'draft', isActive: false, version: 1 }); expect(copy._id.toString()).not.toBe(flow._id.toString()); });
  test('deletes only an owner automation', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition()); expect(await AutomationService.deleteFlow(flow._id, ownerB)).toBe(false); expect(await AutomationService.deleteFlow(flow._id, ownerA)).toBe(true); });
  test('validates trigger, conditions and allowed actions without arbitrary code', async () => { await expect(AutomationService.createFlow(ownerA, definition({ actions: [{ type: 'javascript', config: { code: 'process.exit()' } }] }))).rejects.toThrow('Acción no permitida'); await expect(AutomationService.createFlow(ownerA, definition({ conditions: [{ field: 'password', operator: 'eq', value: 'x' }] }))).rejects.toThrow('Condición no permitida'); });
  test('matches a trigger and executes an action', async () => { await AutomationService.createFlow(ownerA, definition({ status: 'active' })); const executions: any[] = await AutomationEngineService.emit(event()); expect(executions).toHaveLength(1); expect(`${executions[0].status}:${executions[0].error}`).toBe('completed:undefined'); expect((await Lead.findById(lead._id))?.tags).toContain('captado'); });
  test('skips a false condition', async () => { await AutomationService.createFlow(ownerA, definition({ status: 'active', conditions: [{ field: 'platform', operator: 'eq', value: 'facebook' }] })); expect(await AutomationEngineService.emit(event())).toHaveLength(0); });
  test('supports AND conditions', async () => { await AutomationService.createFlow(ownerA, definition({ status: 'active', conditionLogic: 'AND', conditions: [{ field: 'platform', operator: 'eq', value: 'whatsapp' }, { field: 'score', operator: 'gte', value: 60 }] })); expect(await AutomationEngineService.emit(event())).toHaveLength(1); });
  test('supports OR conditions', async () => { await AutomationService.createFlow(ownerA, definition({ status: 'active', conditionLogic: 'OR', conditions: [{ field: 'platform', operator: 'eq', value: 'facebook' }, { field: 'interestLevel', operator: 'eq', value: 'warm' }] })); expect(await AutomationEngineService.emit(event())).toHaveLength(1); });
  test('evaluates step conditions against refreshed lead state', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active', actions: [{ type: 'update_score', config: { score: 80 } }, { type: 'add_tag', config: { tag: 'qualified' }, conditions: [{ field: 'score', operator: 'gte', value: 80 }] }] })); const result: any = await AutomationEngineService.start(flow, event()); expect(result.status).toBe('completed'); expect((await Lead.findById(lead._id))?.tags).toContain('qualified'); });
  test('persists a wait and resumes after a simulated restart', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active', actions: [{ type: 'wait', config: { durationMs: 60000 } }, { type: 'add_tag', config: { tag: 'resumed' } }] })); const execution: any = await AutomationEngineService.start(flow, event()); expect(execution.status).toBe('waiting'); await AutomationJob.updateOne({ executionId: execution._id }, { runAt: new Date(0) }); expect(await AutomationEngineService.processDueJobs()).toBe(1); expect((await Lead.findById(lead._id))?.tags).toContain('resumed'); expect(await AutomationJob.findOne({ executionId: execution._id })).toMatchObject({ status: 'completed' }); });
  test('is idempotent for the same event and automation', async () => { await AutomationService.createFlow(ownerA, definition({ status: 'active' })); await AutomationEngineService.emit(event()); await AutomationEngineService.emit(event()); expect(await AutomationExecution.countDocuments({})).toBe(1); });
  test('retries a safe action before succeeding', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active' })); const original = AutomationEngineService.executeAction; let calls = 0; const spy = jest.spyOn(AutomationEngineService, 'executeAction').mockImplementation(async (...args: any[]) => { calls++; if (calls < 3) throw new Error('transient'); return original.apply(AutomationEngineService, args as any); }); const result: any = await AutomationEngineService.start(flow, event()); expect(result.status).toBe('completed'); expect(spy).toHaveBeenCalledTimes(3); spy.mockRestore(); });
  test('isolates an action failure and records diagnostics', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active', actions: [{ type: 'create_proposal', config: {} }] })); const result: any = await AutomationEngineService.start(flow, event({ platform: 'youtube', recipient: undefined })); expect(result).toMatchObject({ status: 'failed', error: expect.stringContaining('canal privado') }); expect(await AutomationFlow.findById(flow._id)).toMatchObject({ status: 'error' }); });
  test('creates an assisted proposal without outbound delivery', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active', actions: [{ type: 'create_proposal', config: { message: 'Respuesta pendiente de aprobación' } }] })); await AutomationEngineService.start(flow, event()); expect(await AssistedProposal.findOne({})).toMatchObject({ platform: 'whatsapp', status: 'proposed', text: 'Respuesta pendiente de aprobación' }); expect(await OutboundMessage.countDocuments({})).toBe(0); });
  test.each(['youtube', 'whatsapp', 'instagram', 'facebook', 'tiktok'] as const)('accepts normalized multichannel events: %s', async platform => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active', trigger: { type: 'message.received' }, actions: [{ type: 'add_tag', config: { tag: platform } }] })); const result: any = await AutomationEngineService.start(flow, event({ eventId: `event-${platform}`, trigger: 'message.received', platform })); expect(result.status).toBe('completed'); });
  test('creates the INFO qualification template once and inactive', async () => { const first: any = await AutomationService.ensureInfoTemplate(ownerA); const second: any = await AutomationService.ensureInfoTemplate(ownerA); expect(first._id.toString()).toBe(second._id.toString()); expect(first).toMatchObject({ status: 'draft', isActive: false, templateKey: 'info_qualification_v1' }); expect(first.actions.map((item: any) => item.type)).toEqual(expect.arrayContaining(['generate_ai_response', 'wait', 'update_score', 'suggest_followup'])); });
  test('returns execution history only to its owner', async () => { const flow: any = await AutomationService.createFlow(ownerA, definition({ status: 'active' })); await AutomationEngineService.start(flow, event()); expect(await AutomationService.history(flow._id, ownerA)).toHaveLength(1); expect(await AutomationService.history(flow._id, ownerB)).toBeNull(); });
});
