import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import Lead from '../src/models/Lead';
import Conversation from '../src/models/Conversation';
import Task from '../src/models/Task';
import Meeting from '../src/models/Meeting';
import AssistedProposal from '../src/models/AssistedProposal';
import OutboundMessage from '../src/models/OutboundMessage';
import AutomationFlow from '../src/models/AutomationFlow';
import AutomationExecution from '../src/models/AutomationExecution';
import { FollowUpService } from '../src/services/FollowUpService';

describe('Durable assisted lead follow-up', () => {
  let mongo: MongoMemoryServer;
  const now = new Date('2027-01-10T15:00:00.000Z');
  const originalEnv = process.env;

  beforeAll(async () => { mongo = await MongoMemoryServer.create(); await mongoose.connect(mongo.getUri()); });
  beforeEach(() => { process.env = { ...originalEnv, AI_MODE: 'mock', FOLLOWUP_MAX_ATTEMPTS: '3', FOLLOWUP_COOLDOWN_MS: '86400000', META_MESSAGING_MODE: 'mock', WHATSAPP_MESSAGING_MODE: 'mock' }; });
  afterEach(async () => { process.env = originalEnv; await Promise.all([Lead.deleteMany({}), Conversation.deleteMany({}), Task.deleteMany({}), Meeting.deleteMany({}), AssistedProposal.deleteMany({}), OutboundMessage.deleteMany({}), AutomationFlow.deleteMany({}), AutomationExecution.deleteMany({})]); });
  afterAll(async () => { await mongoose.disconnect(); await mongo.stop(); });

  const prepare = async (overrides: any = {}, conversationOverrides: any = {}) => {
    const userId = overrides.userId ?? new mongoose.Types.ObjectId();
    const scheduledAt = new Date(now.getTime() - 2 * 86400000);
    const platform = overrides.platform ?? 'whatsapp';
    const lead: any = await Lead.create({ userId, username: overrides.username ?? `${platform}-person`, phone: platform === 'whatsapp' ? '573001112233' : undefined, platform, currentChannel: platform, status: 'follow_up', interestLevel: 'warm', score: 65, lastContact: scheduledAt, nextFollowUp: new Date(now.getTime() - 1000), followUp: { scheduledAt, attempts: 0 }, qualification: { intent: 'interest', normalizedIntent: 'business_opportunity', meetingIntent: 'medium' }, ...overrides });
    const conversation: any = await Conversation.create({ userId, leadId: lead._id, status: 'active', controlMode: 'automated', lastMessage: new Date(now.getTime() - 86400000), messages: [
      { sender: 'lead', text: 'Me interesa conocer la oportunidad', platform, timestamp: scheduledAt },
      { sender: 'user', text: 'Con gusto, revisa la información y me cuentas', platform, direction: 'outbound', status: 'sent', timestamp: new Date(scheduledAt.getTime() + 1000) },
    ], ...conversationOverrides });
    await Task.create({ userId, leadId: lead._id, conversationId: conversation._id, title: 'Seguimiento anterior', description: 'Pendiente', type: 'follow_up', status: 'pending', dueDate: lead.nextFollowUp, metadata: { autoGenerated: true } });
    return { userId, lead, conversation, scheduledAt };
  };

  test('emits followup.due and creates one contextual assisted proposal without outbound delivery', async () => {
    const { userId, lead } = await prepare();
    await AutomationFlow.create({ userId, name: 'Auditar vencimiento', status: 'active', isActive: true, trigger: { type: 'followup.due' }, actions: [{ type: 'add_tag', config: { tag: 'seguimiento_vencido' } }] });
    expect(await FollowUpService.processDueFollowUps(20, now)).toBe(1);
    expect(await Lead.findById(lead._id)).toMatchObject({ nextFollowUp: null, followUp: { attempts: 1, lastDecision: 'proposed', lastReason: 'due_without_prospect_reply' } });
    expect((await Lead.findById(lead._id))?.tags).toContain('seguimiento_vencido');
    expect(await AutomationExecution.findOne({ trigger: 'followup.due', userId })).not.toBeNull();
    expect(await AssistedProposal.findOne({ userId, leadId: lead._id })).toMatchObject({ platform: 'whatsapp', recipient: { type: 'whatsapp_user', externalId: '573001112233' }, status: 'proposed' });
    expect(await OutboundMessage.countDocuments({})).toBe(0);
    expect(await Task.countDocuments({ userId, leadId: lead._id, status: 'pending' })).toBe(1);
  });

  test('cancels an obsolete task when the prospect replied after scheduling', async () => {
    const prepared = await prepare({}, { messages: [
      { sender: 'user', text: 'Mensaje inicial', platform: 'whatsapp', timestamp: new Date(now.getTime() - 3 * 86400000) },
      { sender: 'lead', text: 'Ya respondí', platform: 'whatsapp', timestamp: new Date(now.getTime() - 86400000) },
    ] });
    await AssistedProposal.create({ userId: prepared.userId, leadId: prepared.lead._id, conversationId: prepared.conversation._id, sourceEventId: `followup:${prepared.lead._id}:old`, platform: 'whatsapp', recipient: { type: 'whatsapp_user', externalId: '573001112233' }, text: 'Seguimiento anterior', originalText: 'Seguimiento anterior', status: 'proposed' });
    await FollowUpService.processDueFollowUps(20, now);
    expect(await Lead.findById(prepared.lead._id)).toMatchObject({ nextFollowUp: null, followUp: { lastDecision: 'cancelled', lastReason: 'prospect_replied_after_schedule', attempts: 0 } });
    expect(await Task.findOne({ leadId: prepared.lead._id })).toMatchObject({ status: 'cancelled', metadata: { cancelReason: 'prospect_replied_after_schedule' } });
    expect(await AssistedProposal.findOne({ leadId: prepared.lead._id })).toMatchObject({ status: 'cancelled', errorMessage: 'Seguimiento cancelado: prospect_replied_after_schedule' });
  });

  test.each([
    ['rejected', { status: 'rejected' }, {}, 'opt_out_or_rejected'],
    ['opt-out', { tags: ['no_contactar'] }, {}, 'opt_out_or_rejected'],
    ['closed', {}, { status: 'closed' }, 'conversation_closed'],
    ['handoff', {}, { controlMode: 'handoff_requested' }, 'handoff_requested'],
    ['human control', {}, { controlMode: 'human_controlled' }, 'human_controlled'],
  ])('omits %s leads and records the reason', async (_name, leadOverrides, conversationOverrides, reason) => {
    const { lead } = await prepare(leadOverrides, conversationOverrides);
    await FollowUpService.processDueFollowUps(20, now);
    expect(await Lead.findById(lead._id)).toMatchObject({ nextFollowUp: null, followUp: { lastDecision: 'cancelled', lastReason: reason, attempts: 0 } });
    expect(await Task.findOne({ leadId: lead._id })).toMatchObject({ status: 'cancelled' });
    expect(await AssistedProposal.countDocuments({})).toBe(0);
  });

  test('detects opt-out language even when the lead state was not updated', async () => {
    const { lead } = await prepare({}, { messages: [{ sender: 'lead', text: 'No quiero continuar, deja de escribir', platform: 'whatsapp', timestamp: new Date(now.getTime() - 86400000) }] });
    await FollowUpService.processDueFollowUps(20, now);
    expect(await Lead.findById(lead._id)).toMatchObject({ followUp: { lastReason: 'opt_out_or_rejected' } });
  });

  test('omits a lead with an active confirmed meeting', async () => {
    const { userId, lead, conversation } = await prepare();
    await Meeting.create({ userId, leadId: lead._id, conversationId: conversation._id, status: 'confirmed', scheduledAt: new Date(now.getTime() + 86400000) });
    await FollowUpService.processDueFollowUps(20, now);
    expect(await Lead.findById(lead._id)).toMatchObject({ followUp: { lastReason: 'active_meeting' } });
    expect(await AssistedProposal.countDocuments({})).toBe(0);
  });

  test('respects maximum attempts and cooldown', async () => {
    const maxed = await prepare({ username: 'maxed', followUp: { attempts: 3 } });
    const cooling = await prepare({ username: 'cooling', followUp: { attempts: 0, nextEligibleAt: new Date(now.getTime() + 3600000) } });
    await FollowUpService.processDueFollowUps(20, now);
    expect(await Lead.findById(maxed.lead._id)).toMatchObject({ followUp: { lastReason: 'max_attempts_reached' } });
    expect(await Lead.findById(cooling.lead._id)).toMatchObject({ nextFollowUp: new Date(now.getTime() + 3600000), followUp: { lastDecision: 'deferred', lastReason: 'cooldown_active' } });
  });

  test('processes multiple due leads once and remains idempotent', async () => {
    await prepare({ username: 'one' }); await prepare({ username: 'two' });
    expect(await FollowUpService.processDueFollowUps(20, now)).toBe(2);
    expect(await FollowUpService.processDueFollowUps(20, now)).toBe(0);
    expect(await AssistedProposal.countDocuments({})).toBe(2);
    expect(await OutboundMessage.countDocuments({})).toBe(0);
  });

  test('allows only one of two concurrent workers to claim a follow-up', async () => {
    const { lead } = await prepare();
    const results = await Promise.all([FollowUpService.processDueFollowUps(1, now), FollowUpService.processDueFollowUps(1, now)]);
    expect(results.reduce((sum, value) => sum + value, 0)).toBe(1);
    expect(await AssistedProposal.countDocuments({ leadId: lead._id })).toBe(1);
    expect((await Lead.findById(lead._id) as any).followUp.attempts).toBe(1);
  });

  test('isolates owners and preserves the current private channel', async () => {
    const instagram = await prepare({ platform: 'instagram', username: 'igsid-1' });
    const facebook = await prepare({ platform: 'facebook', username: 'psid-1' });
    await FollowUpService.processDueFollowUps(20, now);
    expect(await AssistedProposal.findOne({ userId: instagram.userId })).toMatchObject({ platform: 'instagram', recipient: { type: 'instagram_user', externalId: 'igsid-1' } });
    expect(await AssistedProposal.findOne({ userId: facebook.userId })).toMatchObject({ platform: 'facebook', recipient: { type: 'facebook_user', externalId: 'psid-1' } });
  });

  test('creates only an assisted CRM task for YouTube and never publishes', async () => {
    const { lead } = await prepare({ platform: 'youtube', username: 'youtube-thread' });
    await FollowUpService.processDueFollowUps(20, now);
    expect(await Task.findOne({ leadId: lead._id, status: 'pending' })).not.toBeNull();
    expect(await AssistedProposal.countDocuments({})).toBe(0);
    expect(await OutboundMessage.countDocuments({})).toBe(0);
  });
});
