import { classifyHunterCandidate, hunterStatus } from '../src/services/hunter/HunterScoring';

const source = (text: string, field: any = 'channel_description', publishedAt?: string) => ({ text, field, url: 'https://youtube.com/watch?v=test', publishedAt });

describe('Hunter configurable scoring', () => {
  test('detecta perfil comercial fuerte y persona', () => { const r = classifyHunterCandidate([source('Soy asesora comercial y vendedora. Mi experiencia incluye prospección, negociación y cierre de ventas.')]); expect(r.scores.commercial).toBeGreaterThanOrEqual(60); expect(r.entityType).toBe('person'); });
  test('mantiene bajo un perfil comercial débil o educativo', () => expect(classifyHunterCandidate([source('Curso para aprender atención al cliente', 'video_title')]).scores.commercial).toBeLessThan(60));
  test('clasifica empresa o academia como organización', () => expect(classifyHunterCandidate([source('Academia oficial y empresa de formación comercial')]).entityType).toBe('organization'));
  test('conserva unknown sin señales fiables', () => expect(classifyHunterCandidate([source('Canal de ideas y conversaciones')]).entityType).toBe('unknown'));
  test.each(['Busco empleo como vendedor', 'Open to work as sales representative'])(`detecta evidencia laboral explícita: %s`, text => { const r = classifyHunterCandidate([source(text)]); expect(r.jobEvidenceType).toBe('explicit'); expect(r.scores.jobAvailability).toBeGreaterThanOrEqual(60); });
  test('detecta disponibilidad indirecta', () => { const r = classifyHunterCandidate([source('Preparado para mi próximo reto profesional')]); expect(r.jobEvidenceType).toBe('indirect'); expect(r.scores.jobAvailability).toBeGreaterThan(0); });
  test('ausencia laboral queda insufficient', () => expect(classifyHunterCandidate([source('Ventas y nutrición')]).jobEvidenceType).toBe('insufficient'));
  test.each(['No estoy buscando empleo', 'I am not looking for work'])(`respeta negación: %s`, text => { const r = classifyHunterCandidate([source(text)]); expect(r.scores.jobAvailability).toBe(0); expect(r.evidence.some(e => e.possibleNegation)).toBe(true); });
  test('nutrición consistente en varias publicaciones supera mención aislada', () => { const weak = classifyHunterCandidate([source('Una receta de nutrición', 'video_title')]); const strong = classifyHunterCandidate([source('Soy nutricionista y trabajo con alimentación saludable'), source('Suplementación, vitaminas y proteína', 'video_title')]); expect(strong.scores.nutritionWellness).toBeGreaterThan(weak.scores.nutritionWellness); });
  test('detecta venta de productos', () => expect(classifyHunterCandidate([source('Experiencia en venta de productos, retail y recomendación de suplementos')]).scores.productSales).toBeGreaterThan(40));
  test('calcula cuatro scores independientes y coincidencia ponderada', () => { const r = classifyHunterCandidate([source('Soy vendedora y asesora comercial, abierta a nuevas oportunidades, experta en nutrición, bienestar y venta de productos')]); expect(Object.keys(r.scores)).toEqual(['commercial', 'jobAvailability', 'nutritionWellness', 'productSales', 'overall']); expect(r.scores.overall).toBeGreaterThan(0); });
  test('las reglas mínimas impiden score calificado sin disponibilidad', () => { const r = classifyHunterCandidate([source('Soy vendedora, asesora comercial, closer, experta en nutrición, bienestar, suplementación y venta de productos')]); expect(r.scores.jobAvailability).toBe(0); expect(r.scores.overall).toBeLessThan(75); });
  test('expone clasificación visual completa', () => { expect(hunterStatus(90)).toBe('high_priority'); expect(hunterStatus(80)).toBe('good_candidate'); expect(hunterStatus(65)).toBe('review'); expect(hunterStatus(40)).toBe('low_match'); });
  test('conserva fecha y origen de evidencia reciente o antigua y ubicación no es inferida', () => { const date = '2020-01-01T00:00:00.000Z'; const r = classifyHunterCandidate([source('Busco empleo', 'video_description', date)]); expect(r.evidence[0]).toEqual(expect.objectContaining({ publishedAt: date, sourceField: 'video_description' })); expect((r as any).publicLocation).toBeUndefined(); });
});
