import Lead from '../models/Lead';
import Activity from '../models/Activity';
import { ConversationService } from './ConversationService';
import { TaskService } from './TaskService';
import { getAIProvider } from '../integrations/ai';
import { MessagingService } from './MessagingService';
import type { MessagingRecipient } from '../integrations/messaging';
import { MeetingOrchestratorService } from './MeetingOrchestratorService';

type AlmaContext = { userId: string; leadId: string; conversationId: string; text: string; isNewLead: boolean; platform: 'instagram' | 'facebook'; sourceEventId: string; recipient: MessagingRecipient };

export class AlmaService {
  static async processMessage(context: AlmaContext): Promise<string> {
    const normalized = context.text.toLocaleLowerCase('es');
    const wantsMeeting = /\b(cita|reuni[oó]n|zoom|agenda|agendar|llamada)\b/i.test(normalized);
    const isInterested = wantsMeeting || /\b(interesa|precio|informaci[oó]n|info|quiero|c[oó]mo funciona)\b/i.test(normalized);
    const isRejected = /\b(no me interesa|no gracias|deja de escribir|stop)\b/i.test(normalized);

    const score = isRejected ? 0 : wantsMeeting ? 90 : isInterested ? 65 : 30;
    const status = isRejected ? 'rejected' : wantsMeeting ? 'hot_prospect' : isInterested ? 'interested' : 'conversation_started';
    await Lead.findByIdAndUpdate(context.leadId, {
      status,
      score,
      interestLevel: score >= 80 ? 'hot' : score >= 50 ? 'warm' : 'cold',
      lastContact: new Date(),
      nextFollowUp: isRejected ? null : new Date(Date.now() + 24 * 60 * 60 * 1000),
      qualification: { intent: isRejected ? 'rejection' : wantsMeeting ? 'meeting' : isInterested ? 'interest' : 'discovery', meetingRequested: wantsMeeting, lastEvaluatedAt: new Date() },
    });

    const intent = isRejected ? 'rejection' : wantsMeeting ? 'meeting' : isInterested ? 'interest' : 'discovery';
    await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'qualified', description: `Lead calificado con score ${score}`, metadata: { score, status } });
    if (!isRejected) {
      await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'follow_up_scheduled', description: 'Seguimiento programado para 24 horas' });
      await TaskService.upsertPendingFollowUp(context.userId, {
        leadId: context.leadId,
        conversationId: context.conversationId,
        title: 'Hacer seguimiento al prospecto',
        description: 'Revisar la conversación y dar continuidad al lead captado mediante INFO.',
        type: 'follow_up',
        status: 'pending',
        priority: wantsMeeting ? 'high' : 'medium',
        dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
        metadata: { intent, score, autoGenerated: true },
      });
    }

    const aiProvider = getAIProvider();
    const generatedResponse = await aiProvider.generateReply({ incomingText: context.text, isNewLead: context.isNewLead, intent });
    const meetingOutcome = await MeetingOrchestratorService.process({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, sourceEventId: context.sourceEventId, text: context.text, wantsMeeting });
    const response = meetingOutcome.reply ?? generatedResponse;

    await ConversationService.addMessage(context.conversationId, context.userId, { sender: 'ai', text: response, platform: context.platform });
    await MessagingService.send({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, sourceEventId: context.sourceEventId, text: response, recipient: context.recipient });
    await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'message_generated', description: 'ALMA generó y procesó una respuesta saliente', metadata: { aiProvider: aiProvider.name } });
    return response;
  }
}
