import Lead from '../models/Lead';
import Activity from '../models/Activity';
import Meeting from '../models/Meeting';
import { ConversationService } from './ConversationService';
import { TaskService } from './TaskService';
import { getAIProvider } from '../integrations/ai';
import { getMeetingProvider } from '../integrations/meetings';

type AlmaContext = { userId: string; leadId: string; conversationId: string; text: string; isNewLead: boolean; platform: 'instagram' | 'facebook' };

export class AlmaService {
  static async processMessage(context: AlmaContext): Promise<string> {
    const normalized = context.text.toLocaleLowerCase('es');
    const wantsMeeting = /\b(cita|reuni[oó]n|zoom|agenda|agendar|llamada)\b/i.test(normalized);
    const isInterested = wantsMeeting || /\b(interesa|precio|informaci[oó]n|info|quiero|c[oó]mo funciona)\b/i.test(normalized);
    const isRejected = /\b(no me interesa|no gracias|deja de escribir|stop)\b/i.test(normalized);

    const score = isRejected ? 0 : wantsMeeting ? 90 : isInterested ? 65 : 30;
    const status = isRejected ? 'rejected' : wantsMeeting ? 'hot_prospect' : isInterested ? 'interested' : 'conversation_started';
    await Lead.findByIdAndUpdate(context.leadId, {
      status,
      score,
      interestLevel: score >= 80 ? 'hot' : score >= 50 ? 'warm' : 'cold',
      lastContact: new Date(),
      nextFollowUp: isRejected ? null : new Date(Date.now() + 24 * 60 * 60 * 1000),
      qualification: { intent: isRejected ? 'rejection' : wantsMeeting ? 'meeting' : isInterested ? 'interest' : 'discovery', meetingRequested: wantsMeeting, lastEvaluatedAt: new Date() },
    });

    const intent = isRejected ? 'rejection' : wantsMeeting ? 'meeting' : isInterested ? 'interest' : 'discovery';
    await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'qualified', description: `Lead calificado con score ${score}`, metadata: { score, status } });
    if (!isRejected) {
      await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'follow_up_scheduled', description: 'Seguimiento programado para 24 horas' });
      await TaskService.createTask(context.userId, {
        leadId: context.leadId,
        conversationId: context.conversationId,
        title: 'Hacer seguimiento al prospecto',
        description: 'Revisar la conversación y dar continuidad al lead captado mediante INFO.',
        type: 'follow_up',
        status: 'pending',
        priority: wantsMeeting ? 'high' : 'medium',
        dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
        metadata: { intent, score, autoGenerated: true },
      });
    }

    const aiProvider = getAIProvider();
    const response = await aiProvider.generateReply({ incomingText: context.text, isNewLead: context.isNewLead, intent });
    if (wantsMeeting) {
      const meetingProvider = getMeetingProvider();
      const result = await meetingProvider.createMeeting({ topic: 'Reunión de descubrimiento con ALMA', timezone: 'America/Bogota' });
      await Meeting.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, status: result.simulated ? 'pending_configuration' : 'scheduled', topic: 'Reunión de descubrimiento con ALMA', externalId: result.externalId, joinUrl: result.joinUrl });
      await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'meeting_requested', description: 'El prospecto solicitó una reunión por Zoom' });
      await TaskService.createTask(context.userId, {
        leadId: context.leadId,
        conversationId: context.conversationId,
        title: 'Confirmar reunión de descubrimiento',
        description: 'Revisar y completar la programación de la reunión generada por ALMA.',
        type: 'meeting',
        status: 'pending',
        priority: 'high',
        dueDate: new Date(Date.now() + 2 * 60 * 60 * 1000),
        metadata: { externalId: result.externalId, joinUrl: result.joinUrl, autoGenerated: true },
      });
    }

    await ConversationService.addMessage(context.conversationId, context.userId, { sender: 'ai', text: response, platform: context.platform });
    await Activity.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, type: 'message_generated', description: 'ALMA generó una respuesta', metadata: { provider: aiProvider.name, simulatedDelivery: true } });
    return response;
  }
}
