import Meeting from '../models/Meeting';
import Task from '../models/Task';
import { TaskService } from './TaskService';
import { MeetingAvailabilityService } from './MeetingAvailabilityService';
import { getMeetingProvider, MeetingProviderError, type MeetingProvider } from '../integrations/meetings';
import { AutomationEngineService, type AutomationTrigger } from './AutomationEngineService';
import MeetingAction from '../models/MeetingAction';
import AssistedProposal from '../models/AssistedProposal';
import { MeetingAutomationPolicyService } from './MeetingAutomationService';

export type MeetingLifecycleContext = { userId: string; leadId: string; conversationId: string; sourceEventId: string; platform?: 'instagram' | 'facebook' | 'youtube' | 'whatsapp'; timezone?: string; attendeeEmail?: string };
export class MeetingLifecycleService {
  constructor(private readonly provider: MeetingProvider = getMeetingProvider()) {}
  static hasSufficientIntent(text: string): boolean { return /\b(quiero|quisiera|podemos|necesito|deseo|me gustaria|me gustaría|agenda|agendar|programar|reservar|confirmo)\b.{0,35}\b(cita|reunion|reunión|zoom|llamada|horario)\b|\b(agenda|agendar|programar|reservar)\b/i.test(text); }
  static isLowIntent(text: string): boolean { return /\b(quiza|quizá|tal vez|de pronto|algun dia|algún día)\b/i.test(text) && !this.hasSufficientIntent(text); }
  private async emit(meeting: any, trigger: AutomationTrigger) { await AutomationEngineService.emit({ eventId: `meeting:${meeting._id}:${trigger}:${meeting.updatedAt?.getTime?.() || Date.now()}`, trigger, userId: meeting.userId.toString(), leadId: meeting.leadId.toString(), conversationId: meeting.conversationId?.toString(), platform: meeting.originChannel as any, data: { meetingIntent: 'high', meetingId: meeting._id.toString(), status: meeting.status } }); }

  async propose(context: MeetingLifecycleContext): Promise<{ meeting: any; reply: string }> {
    let meeting: any = await Meeting.findOne({ userId: context.userId, conversationId: context.conversationId, status: { $in: ['potential', 'requested', 'pending_confirmation', 'reschedule_requested', 'failed', 'pending_details', 'pending_configuration'] } }).sort({ createdAt: -1 });
    if (!meeting) meeting = await Meeting.create({ userId: context.userId, leadId: context.leadId, conversationId: context.conversationId, provider: 'zoom', status: 'requested', requestedAt: new Date(), sourceEventId: context.sourceEventId, timezone: context.timezone || MeetingAvailabilityService.config().timezone, durationMinutes: MeetingAvailabilityService.config().durationMinutes, attendeeEmail: context.attendeeEmail, originChannel: context.platform, topic: 'Reunión de descubrimiento con ALMA', lifecycleHistory: [{ status: 'requested', reason: 'conversational_intent' }] });
    if (meeting.status === 'pending_configuration' && meeting.selectedSlot) return { meeting, reply: 'La reunión ya está pendiente de activación de Zoom; no crearé otra.' };
    if (context.timezone) meeting.timezone = context.timezone; if (context.attendeeEmail) meeting.attendeeEmail = context.attendeeEmail;
    const slots = await MeetingAvailabilityService.options(context.userId, meeting.timezone); meeting.status = meeting.status === 'reschedule_requested' ? 'reschedule_requested' : 'pending_confirmation'; meeting.proposedSlots = slots; meeting.optionsExpiresAt = new Date(Date.now() + MeetingAutomationPolicyService.optionsTtlMs()); meeting.requestedAt ||= new Date(); meeting.lifecycleHistory.push({ status: meeting.status, reason: 'availability_proposed' }); await meeting.save();
    await this.emit(meeting, 'meeting.requested');
    if (!slots.length) return { meeting, reply: 'Recibí tu solicitud, pero no hay horarios disponibles en la ventana configurada. La revisaré manualmente.' };
    const formatted = slots.map((slot: Date, index: number) => `${index + 1}. ${MeetingAvailabilityService.format(slot, meeting.timezone)}`).join('\n');
    return { meeting, reply: `Tengo estos horarios disponibles:\n${formatted}\nResponde con el número de la opción que prefieres.` };
  }

  async select(context: MeetingLifecycleContext, selection: number): Promise<{ meeting: any; reply: string }> {
    const meeting: any = await Meeting.findOne({ userId: context.userId, conversationId: context.conversationId, status: { $in: ['pending_confirmation', 'reschedule_requested'] } }); if (!meeting) throw new Error('No hay una propuesta de horarios activa');
    if (meeting.optionsExpiresAt && meeting.optionsExpiresAt <= new Date()) { meeting.proposedSlots = []; meeting.selectedSlot = undefined; await meeting.save(); return this.propose(context); }
    const slot = meeting.proposedSlots?.[selection - 1]; if (!slot) throw new Error('La opción seleccionada no existe');
    if (!await MeetingAvailabilityService.isAvailable(context.userId, slot, meeting.durationMinutes, 0, MeetingAvailabilityService.config().bufferAfterMinutes, meeting._id.toString())) return this.propose(context);
    meeting.selectedSlot = slot; meeting.confirmationRequestedAt = new Date(); meeting.lifecycleHistory.push({ status: 'pending_confirmation', reason: `slot_${selection}_selected` }); await meeting.save();
    return { meeting, reply: `Seleccionaste ${MeetingAvailabilityService.format(slot, meeting.timezone)}. Responde “confirmo” para crear la reunión en Zoom.` };
  }

  async confirm(context: MeetingLifecycleContext): Promise<{ meeting: any; reply: string }> {
    const existing: any = await Meeting.findOne({ userId: context.userId, conversationId: context.conversationId }).sort({ createdAt: -1 }).select('+startUrl');
    if (!existing) throw new Error('No hay una solicitud de reunión');
    if (existing.optionsExpiresAt && existing.optionsExpiresAt <= new Date()) { existing.proposedSlots = []; existing.selectedSlot = undefined; existing.status = 'pending_confirmation'; await existing.save(); return this.propose(context); }
    if (['confirmed', 'scheduled'].includes(existing.status) && existing.externalMeetingId) return { meeting: existing, reply: 'La reunión ya estaba confirmada. Los datos permanecen disponibles en el CRM.' };
    if (existing.status === 'pending_configuration') return { meeting: existing, reply: 'La selección ya está registrada y Zoom continúa en modo de prueba.' };
    if (existing.status === 'failed' && ['ZOOM_TIMEOUT', 'ZOOM_CREATE_MEETING_ERROR', 'MEETING_UNKNOWN_ERROR'].includes(existing.errorCode || '')) return { meeting: existing, reply: 'El resultado anterior de Zoom es ambiguo. Verifica Zoom manualmente antes de intentar otra creación.' };
    if (!existing.selectedSlot) throw new Error('Primero debes seleccionar un horario');
    const available = await MeetingAvailabilityService.isAvailable(context.userId, existing.selectedSlot, existing.durationMinutes, 0, MeetingAvailabilityService.config().bufferAfterMinutes, existing._id.toString());
    if (!available) { existing.selectedSlot = undefined; existing.proposedSlots = []; existing.status = 'pending_confirmation'; await existing.save(); return this.propose(context); }
    let claimed: any;
    try {
      claimed = await Meeting.findOneAndUpdate({ _id: existing._id, userId: context.userId, status: { $in: ['pending_confirmation', 'reschedule_requested', 'failed'] }, $or: [{ externalMeetingId: { $exists: false } }, { status: 'reschedule_requested' }] }, { $set: { status: 'requested', scheduledAt: existing.selectedSlot, reservationKey: `${context.userId}:${new Date(existing.selectedSlot).toISOString()}`, error: null, errorCode: null, errorMessage: null }, $inc: { confirmationAttempts: 1 }, $push: { lifecycleHistory: { status: 'requested', at: new Date(), reason: 'confirmation_claimed' } } }, { new: true }).select('+startUrl');
    } catch (error: any) {
      if (error?.code !== 11000) throw error;
      existing.selectedSlot = undefined; existing.proposedSlots = []; existing.status = 'pending_confirmation';
      await existing.save();
      return this.propose(context);
    }
    if (!claimed) return { meeting: existing, reply: 'La confirmación ya está siendo procesada; no crearé una segunda reunión.' };
    try {
      const request = { topic: claimed.topic, scheduledFor: claimed.selectedSlot, timezone: claimed.timezone, durationMinutes: claimed.durationMinutes, agenda: `Contacto: ${claimed.attendeeEmail || 'CRM'}` };
      const result = existing.status === 'reschedule_requested' && existing.externalMeetingId && this.provider.updateMeeting ? await this.provider.updateMeeting(existing.externalMeetingId, request) : await this.provider.createMeeting(request);
      claimed.status = result.simulated ? 'pending_configuration' : 'confirmed'; claimed.scheduledAt = result.scheduledFor || claimed.selectedSlot; claimed.scheduledFor = claimed.scheduledAt; claimed.optionsExpiresAt = undefined; claimed.externalMeetingId = result.externalId; claimed.externalId = result.externalId; claimed.joinUrl = result.joinUrl || existing.joinUrl; claimed.startUrl = result.startUrl; claimed.lifecycleHistory.push({ status: claimed.status, reason: result.simulated ? 'zoom_mock' : 'zoom_created' }); await claimed.save();
      await TaskService.createTask(context.userId, { leadId: context.leadId, conversationId: context.conversationId, title: result.simulated ? 'Confirmar Zoom al activar live' : 'Preparar reunión', description: `Horario: ${MeetingAvailabilityService.format(claimed.scheduledAt, claimed.timezone)}`, type: 'meeting', status: 'pending', priority: 'high', dueDate: claimed.scheduledAt, metadata: { meetingId: claimed._id.toString(), autoGenerated: true } });
      if (!result.simulated) await this.emit(claimed, 'meeting.confirmed');
      return { meeting: claimed, reply: result.simulated ? 'Horario confirmado en ALMA. Zoom está en modo mock, por lo que no se creó una reunión real.' : `Reunión confirmada para ${MeetingAvailabilityService.format(claimed.scheduledAt, claimed.timezone)}. Los datos de acceso están guardados en el CRM.` };
    } catch (error) { const normalized = error instanceof MeetingProviderError ? error : new MeetingProviderError('No fue posible crear la reunión', 'MEETING_UNKNOWN_ERROR'); claimed.status = 'failed'; claimed.error = normalized.message; claimed.errorCode = normalized.code; claimed.errorMessage = normalized.message; claimed.failedAt = new Date(); claimed.lifecycleHistory.push({ status: 'failed', reason: normalized.code }); await claimed.save(); await this.emit(claimed, 'meeting.failed'); return { meeting: claimed, reply: 'No pude crear la reunión. La solicitud quedó guardada para un reintento seguro.' }; }
  }

  async cancel(userId: string, meetingId: string) { const meeting: any = await Meeting.findOne({ _id: meetingId, userId }); if (!meeting) return null; if (meeting.externalMeetingId && !meeting.externalMeetingId.startsWith('mock-') && this.provider.cancelMeeting) await this.provider.cancelMeeting(meeting.externalMeetingId); meeting.status = 'cancelled'; meeting.reservationKey = undefined; meeting.outcome = { type: 'cancelled', actor: 'unknown', reason: 'controlled_cancellation', recordedAt: new Date(), recordedBy: 'crm_or_conversation' }; meeting.lifecycleHistory.push({ status: 'cancelled', reason: 'controlled_cancellation' }); await meeting.save(); await this.invalidateScheduledArtifacts(meeting, 'meeting_cancelled'); return meeting; }
  async requestReschedule(context: MeetingLifecycleContext) { const meeting: any = await Meeting.findOneAndUpdate({ userId: context.userId, conversationId: context.conversationId, status: { $in: ['confirmed', 'scheduled', 'pending_configuration'] } }, { $set: { status: 'reschedule_requested', proposedSlots: [], selectedSlot: null, optionsExpiresAt: null }, $push: { lifecycleHistory: { status: 'reschedule_requested', at: new Date(), reason: 'prospect_request' } } }, { new: true }); if (!meeting) throw new Error('No hay una reunión reprogramable'); await this.invalidateScheduledArtifacts(meeting, 'meeting_rescheduled'); return this.propose(context); }
  async complete(userId: string, meetingId: string) { const now = new Date(); const meeting: any = await Meeting.findOneAndUpdate({ _id: meetingId, userId, status: { $in: ['confirmed', 'scheduled', 'pending_review'] } }, { $set: { status: 'completed', outcome: { type: 'attended', actor: 'unknown', reason: 'crm_completed', recordedAt: now, recordedBy: 'human' } }, $push: { lifecycleHistory: { status: 'completed', at: now, reason: 'crm_completed' } } }, { new: true }); if (meeting) { await this.invalidateScheduledArtifacts(meeting, 'meeting_completed'); await this.emit(meeting, 'meeting.completed'); } return meeting; }
  async markNoShow(userId: string, meetingId: string, actor: 'prospect' | 'host' | 'unknown', reason?: string) { const now = new Date(); const meeting: any = await Meeting.findOneAndUpdate({ _id: meetingId, userId, status: { $in: ['confirmed', 'scheduled', 'pending_review'] } }, { $set: { status: 'no_show', outcome: { type: 'no_show', actor, reason: reason?.slice(0, 500), recordedAt: now, recordedBy: 'human' } }, $push: { lifecycleHistory: { status: 'no_show', at: now, reason: reason?.slice(0, 500) || `no_show_${actor}` } } }, { new: true }); if (meeting) { await this.invalidateScheduledArtifacts(meeting, 'meeting_no_show'); await this.emit(meeting, 'meeting.no_show'); } return meeting; }
  async markTechnicalFailure(userId: string, meetingId: string, reason?: string) { const now = new Date(); const meeting: any = await Meeting.findOneAndUpdate({ _id: meetingId, userId, status: { $in: ['confirmed', 'scheduled', 'pending_review', 'failed'] } }, { $set: { status: 'failed', errorCode: 'MEETING_TECHNICAL_FAILURE', errorMessage: reason?.slice(0, 500) || 'Fallo técnico confirmado por revisión humana', failedAt: now, outcome: { type: 'technical_failure', actor: 'unknown', reason: reason?.slice(0, 500), recordedAt: now, recordedBy: 'human' } }, $push: { lifecycleHistory: { status: 'failed', at: now, reason: 'technical_failure_confirmed' } } }, { new: true }); if (meeting) { await this.invalidateScheduledArtifacts(meeting, 'meeting_technical_failure'); await this.emit(meeting, 'meeting.failed'); } return meeting; }
  private async invalidateScheduledArtifacts(meeting: any, reason: string) { const actions: any[] = await MeetingAction.find({ userId: meeting.userId, meetingId: meeting._id, kind: 'reminder', status: { $in: ['pending', 'processing', 'completed'] } }).select('_id proposalId taskId'); await MeetingAction.updateMany({ _id: { $in: actions.map(item => item._id) }, status: { $in: ['pending', 'processing'] } }, { $set: { status: 'cancelled', reason, completedAt: new Date() } }); const proposalIds = actions.map(item => item.proposalId).filter(Boolean); const taskIds = actions.map(item => item.taskId).filter(Boolean); if (proposalIds.length) await AssistedProposal.updateMany({ _id: { $in: proposalIds }, status: { $in: ['proposed', 'failed'] } }, { $set: { status: 'cancelled', invalidationReason: reason, invalidatedAt: new Date(), errorMessage: `Propuesta de reunión caducada: ${reason}` } }); if (taskIds.length) await Task.updateMany({ _id: { $in: taskIds }, status: 'pending' }, { $set: { status: 'cancelled' } }); await Task.updateMany({ userId: meeting.userId, 'metadata.meetingId': meeting._id.toString(), 'metadata.meetingActionKind': { $exists: false }, status: 'pending' }, { $set: { status: reason === 'meeting_completed' ? 'completed' : 'cancelled' } }); }
}
