import { Router } from 'express';
import { AutomationController } from '../controllers/AutomationController';
import { authMiddleware } from '../middlewares/auth';
import { apiLimiter } from '../middlewares/rateLimiter';

const router = Router();
router.use(authMiddleware, apiLimiter);
router.get('/', AutomationController.list);
router.post('/templates/info-qualification', AutomationController.template);
router.post('/templates/additional-income-assisted', AutomationController.additionalIncomeTemplate);
router.post('/templates/product-interest-assisted', AutomationController.productInterestTemplate);
router.post('/templates/product-sales-assisted', AutomationController.productSalesTemplate);
router.post('/templates/business-opportunity-assisted', AutomationController.businessOpportunityTemplate);
router.post('/templates/business-product-assisted', AutomationController.businessProductTemplate);
router.post('/', AutomationController.create);
router.get('/:id', AutomationController.get);
router.put('/:id', AutomationController.update);
router.patch('/:id/status', AutomationController.status);
router.patch('/:id/toggle', AutomationController.toggle);
router.post('/:id/duplicate', AutomationController.duplicate);
router.post('/:id/test', AutomationController.test);
router.get('/:id/executions', AutomationController.history);
router.delete('/:id', AutomationController.remove);
export default router;
