import { FormEvent, useEffect, useState } from 'react';
import { AppLayout } from '@components/AppLayout';
import { Button, Card, Badge } from '@components/shared';
import { Modal } from '@components/advanced';
import { automationService, type AutomationExecution, type AutomationFlow, type AutomationInput, type AutomationStatus } from '@services/automationService';

type ActionRow = { type: string; value: string };
const blank = () => ({ name: '', description: '', triggerType: 'keyword.detected', keywords: 'INFO', platform: '', actions: [{ type: 'create_proposal', value: '' }] as ActionRow[], conditionLogic: 'AND' as 'AND' | 'OR', conditionField: '', conditionOperator: 'eq', conditionValue: '' });
const statuses: AutomationStatus[] = ['draft', 'active', 'paused', 'disabled', 'error'];
const triggers = ['lead.created', 'message.received', 'keyword.detected', 'lead.score_changed', 'lead.status_changed', 'lead.qualification_changed', 'conversation.updated', 'followup.due', 'meeting.intent_detected', 'meeting.requested', 'meeting.confirmed', 'meeting.failed', 'meeting.completed', 'meeting.reminder_due', 'meeting.no_show', 'meeting.followup_due'];
const actionTypes = ['generate_ai_response', 'create_proposal', 'add_tag', 'change_status', 'update_score', 'create_task', 'suggest_followup', 'mark_meeting_candidate', 'add_note', 'wait'];
const conditionFields = ['', 'leadId', 'platform', 'source', 'keyword', 'score', 'interestLevel', 'status', 'tags', 'intent', 'normalizedIntent', 'normalizedIntents', 'commercialContextId', 'meetingIntent', 'lastInteractionAt', 'targetProfile', 'affinities'];

export const AutomationPage = () => {
  const [flows, setFlows] = useState<AutomationFlow[]>([]); const [open, setOpen] = useState(false); const [editing, setEditing] = useState<AutomationFlow | null>(null);
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [form, setForm] = useState(blank());
  const [statusFilter, setStatusFilter] = useState(''); const [triggerFilter, setTriggerFilter] = useState(''); const [search, setSearch] = useState('');
  const [history, setHistory] = useState<{ name: string; items: AutomationExecution[] } | null>(null);
  const load = async () => { setLoading(true); try { setFlows(await automationService.list({ status: statusFilter || undefined, trigger: triggerFilter || undefined, search: search || undefined })); } catch { setMessage('No fue posible cargar las automatizaciones.'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [statusFilter, triggerFilter]);
  const keywords = () => form.keywords.split(/[\n,]/).map(value => value.trim()).filter(Boolean);
  const config = (action: ActionRow) => action.type === 'add_tag' ? { tag: action.value } : action.type === 'update_score' ? { score: Number(action.value) } : action.type === 'change_status' ? { status: action.value } : action.type === 'wait' ? { durationMs: Number(action.value) } : { message: action.value };
  const payload = (): AutomationInput => ({ name: form.name, description: form.description, status: editing?.status ?? 'draft', trigger: { type: form.triggerType, keyword: form.triggerType === 'keyword.detected' ? keywords()[0] : undefined, keywords: form.triggerType === 'keyword.detected' ? keywords() : undefined, platform: form.platform || undefined }, conditionLogic: form.conditionLogic, conditions: form.conditionField ? [{ field: form.conditionField, operator: form.conditionOperator, value: ['score', 'lastInteractionAt'].includes(form.conditionField) ? Number(form.conditionValue) : form.conditionValue }] : [], actions: form.actions.map(action => ({ type: action.type, config: config(action) })) });
  const close = () => { setOpen(false); setEditing(null); setForm(blank()); };
  const save = async (event: FormEvent) => { event.preventDefault(); setLoading(true); try { const saved = editing ? await automationService.update(editing._id, payload()) : await automationService.create(payload()); setFlows(current => editing ? current.map(item => item._id === saved._id ? saved : item) : [saved, ...current]); setMessage(editing ? 'Automatización actualizada.' : 'Automatización guardada como borrador.'); close(); } catch (error: any) { setMessage(error?.response?.data?.message || 'No fue posible guardar.'); } finally { setLoading(false); } };
  const edit = (flow: AutomationFlow) => { const condition = flow.conditions?.[0]; setEditing(flow); setForm({ name: flow.name, description: flow.description || '', triggerType: flow.trigger.type, keywords: (flow.trigger.keywords?.length ? flow.trigger.keywords : flow.trigger.keyword ? [flow.trigger.keyword] : []).join('\n'), platform: flow.trigger.platform || '', actions: flow.actions.map(action => ({ type: action.type, value: String(action.config?.message ?? action.config?.tag ?? action.config?.score ?? action.config?.status ?? action.config?.durationMs ?? '') })), conditionLogic: flow.conditionLogic || 'AND', conditionField: condition?.field || '', conditionOperator: condition?.operator || 'eq', conditionValue: condition?.value == null ? '' : String(condition.value) }); setOpen(true); };
  const changeStatus = async (flow: AutomationFlow, status: AutomationStatus) => { const updated = await automationService.setStatus(flow._id, status); setFlows(current => current.map(item => item._id === flow._id ? updated : item)); };
  const duplicate = async (flow: AutomationFlow) => { const copy = await automationService.duplicate(flow._id); setFlows(current => [copy, ...current]); };
  const remove = async (flow: AutomationFlow) => { if (!window.confirm(`¿Eliminar “${flow.name}”?`)) return; await automationService.remove(flow._id); setFlows(current => current.filter(item => item._id !== flow._id)); };
  const createTemplate = async () => { const flow = await automationService.createInfoTemplate(); setFlows(current => [flow, ...current.filter(item => item._id !== flow._id)]); setMessage('Plantilla INFO creada como borrador; revísala antes de activarla.'); };
  const createAdditionalIncomeTemplate = async () => { const flow = await automationService.createAdditionalIncomeTemplate(); setFlows(current => [flow, ...current.filter(item => item._id !== flow._id)]); setMessage('Plantilla comercial creada como borrador; actívala únicamente después de revisarla.'); };
  const createProductInterestTemplate = async () => { const flow = await automationService.createProductInterestTemplate(); setFlows(current => [flow, ...current.filter(item => item._id !== flow._id)]); setMessage('Plantilla de consumo creada como borrador; actívala únicamente después de revisarla.'); };
  const createProductSalesTemplate = async () => { const flow = await automationService.createProductSalesTemplate(); setFlows(current => [flow, ...current.filter(item => item._id !== flow._id)]); setMessage('Plantilla de venta de productos creada como borrador; actívala únicamente después de revisarla.'); };
  const createBusinessOpportunityTemplate = async () => { const flow = await automationService.createBusinessOpportunityTemplate(); setFlows(current => [flow, ...current.filter(item => item._id !== flow._id)]); setMessage('Plantilla de oportunidad de negocio creada como borrador; actívala únicamente después de revisarla.'); };
  const createBusinessProductTemplate = async () => { const flow = await automationService.createBusinessProductTemplate(); setFlows(current => [flow, ...current.filter(item => item._id !== flow._id)]); setMessage('Plantilla de interés combinado creada como borrador; actívala únicamente después de revisarla.'); };
  return <AppLayout title="Automatizaciones" subtitle="Motor multicanal persistente con aprobación humana para mensajería."><div className="space-y-6">
    <Card hover={false}><div className="flex flex-wrap items-end gap-3"><div className="mr-auto"><h2 className="text-2xl font-semibold text-white">Automatizaciones</h2><p className="text-dark-400">Trigger → condiciones → acciones → espera → evaluación.</p></div><Button variant="secondary" onClick={() => void createBusinessProductTemplate()}>Plantilla interés combinado</Button><Button variant="secondary" onClick={() => void createBusinessOpportunityTemplate()}>Plantilla oportunidad de negocio</Button><Button variant="secondary" onClick={() => void createProductSalesTemplate()}>Plantilla venta de productos</Button><Button variant="secondary" onClick={() => void createProductInterestTemplate()}>Plantilla interés en productos</Button><Button variant="secondary" onClick={() => void createAdditionalIncomeTemplate()}>Plantilla ingresos adicionales</Button><Button variant="secondary" onClick={() => void createTemplate()}>Plantilla INFO</Button><Button onClick={() => setOpen(true)}>Crear nueva</Button></div><div className="mt-4 grid gap-3 md:grid-cols-4"><Input label="Buscar" value={search} onChange={setSearch} /><Select label="Estado" value={statusFilter} onChange={setStatusFilter} options={['', ...statuses]} /><Select label="Trigger" value={triggerFilter} onChange={setTriggerFilter} options={['', ...triggers]} /><Button variant="secondary" onClick={() => void load()}>Filtrar</Button></div>{message && <p className="mt-4 text-sm text-primary-300">{message}</p>}</Card>
    <div className="space-y-4">{flows.map(flow => <Card key={flow._id} hover={false}><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="grow"><h3 className="text-xl font-semibold text-white">{flow.name}</h3><p className="text-sm text-dark-400">{flow.trigger.type} · {(flow.trigger.keywords ?? [flow.trigger.keyword]).filter(Boolean).join(', ') || 'sin keywords'} · {flow.trigger.platform || 'multicanal'}</p><p className="mt-1 text-xs text-dark-500">{flow.actions.length} acciones · última ejecución: {flow.lastRunAt ? new Date(flow.lastRunAt).toLocaleString() : 'Nunca'} · versión {flow.version || 1}</p><div className="mt-2 flex gap-2 text-xs"><span>{flow.executionStats?.totalExecutions || 0} ejecuciones</span><span className="text-green-300">{flow.executionStats?.successfulExecutions || 0} éxitos</span><span className="text-red-300">{flow.executionStats?.failedExecutions || 0} errores</span></div></div><Badge variant={flow.status === 'active' ? 'success' : flow.status === 'error' ? 'danger' : 'warning'}>{flow.status}</Badge><div className="flex flex-wrap gap-2"><Button size="sm" variant="secondary" onClick={() => edit(flow)}>Editar</Button><Button size="sm" variant="secondary" onClick={() => void duplicate(flow)}>Duplicar</Button><Button size="sm" variant="secondary" onClick={async () => setHistory({ name: flow.name, items: await automationService.history(flow._id) })}>Historial</Button>{flow.status === 'active' ? <Button size="sm" variant="secondary" onClick={() => void changeStatus(flow, 'paused')}>Pausar</Button> : <Button size="sm" onClick={() => void changeStatus(flow, 'active')}>{flow.status === 'paused' ? 'Reactivar' : 'Activar'}</Button>}<Button size="sm" variant="danger" onClick={() => void remove(flow)}>Eliminar</Button></div></div></Card>)}{!loading && !flows.length && <Card hover={false}><p className="text-dark-400">No hay automatizaciones con estos filtros.</p></Card>}</div>
  </div><Modal isOpen={open} onClose={close} title={editing ? 'Editar automatización' : 'Nueva automatización'} size="lg"><form onSubmit={save} className="space-y-4"><Input label="Nombre" value={form.name} onChange={value => setForm({ ...form, name: value })} required /><Input label="Descripción" value={form.description} onChange={value => setForm({ ...form, description: value })} /><Select label="Trigger" value={form.triggerType} onChange={value => setForm({ ...form, triggerType: value })} options={triggers} />{form.triggerType === 'keyword.detected' && <Input label="Keywords/frases (separadas por coma)" value={form.keywords} onChange={value => setForm({ ...form, keywords: value })} required />}<Select label="Plataforma (vacío = todas)" value={form.platform} onChange={value => setForm({ ...form, platform: value })} options={['', 'youtube', 'whatsapp', 'instagram', 'facebook', 'tiktok']} /><div className="grid gap-3 md:grid-cols-3"><Select label="Condición" value={form.conditionField} onChange={value => setForm({ ...form, conditionField: value })} options={conditionFields} /><Select label="Operador" value={form.conditionOperator} onChange={value => setForm({ ...form, conditionOperator: value })} options={['eq', 'neq', 'contains', 'in', 'gte', 'lte', 'exists', 'elapsed_gte']} /><Input label="Valor" value={form.conditionValue} onChange={value => setForm({ ...form, conditionValue: value })} /></div><Select label="Lógica" value={form.conditionLogic} onChange={value => setForm({ ...form, conditionLogic: value as 'AND' | 'OR' })} options={['AND', 'OR']} /><div className="space-y-3"><p className="text-sm text-dark-300">Acciones ({form.actions.length})</p>{form.actions.map((action, index) => <div key={index} className="grid gap-3 rounded-xl border border-dark-700 p-3 md:grid-cols-[1fr_1fr_auto]"><Select label={`Acción ${index + 1}`} value={action.type} onChange={value => setForm({ ...form, actions: form.actions.map((item, i) => i === index ? { ...item, type: value } : item) })} options={actionTypes} /><Input label="Configuración/valor" value={action.value} onChange={value => setForm({ ...form, actions: form.actions.map((item, i) => i === index ? { ...item, value } : item) })} /><Button type="button" variant="danger" onClick={() => setForm({ ...form, actions: form.actions.filter((_, i) => i !== index) })} disabled={form.actions.length === 1}>Quitar</Button></div>)}<Button type="button" variant="secondary" onClick={() => setForm({ ...form, actions: [...form.actions, { type: 'add_tag', value: '' }] })}>Agregar acción</Button></div><p className="text-xs text-amber-300">Las respuestas quedan como propuestas; nunca se envían automáticamente.</p><div className="flex justify-end gap-3"><Button type="button" variant="secondary" onClick={close}>Cancelar</Button><Button type="submit" loading={loading}>Guardar</Button></div></form></Modal>
  <Modal isOpen={Boolean(history)} onClose={() => setHistory(null)} title={`Historial · ${history?.name || ''}`} size="lg"><div className="max-h-96 space-y-3 overflow-y-auto">{history?.items.map(item => <div key={item._id} className="rounded-xl bg-dark-900 p-3"><p className="text-sm text-white">{item.status} · {item.trigger}</p><p className="text-xs text-dark-400">{new Date(item.startedAt).toLocaleString()} · {item.steps.length} pasos</p>{item.error && <p className="text-xs text-red-300">{item.error}</p>}</div>)}{history && !history.items.length && <p className="text-dark-400">Sin ejecuciones.</p>}</div></Modal></AppLayout>;
};
const Input = ({ label, value, onChange, required = false }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) => <label className="block text-sm text-dark-300">{label}<input required={required} value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-dark-600 bg-dark-900 px-3 py-2 text-white" /></label>;
const Select = ({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: readonly string[] }) => <label className="block text-sm text-dark-300">{label}<select value={value} onChange={event => onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-dark-600 bg-dark-900 px-3 py-2 text-white">{options.map(option => <option key={option} value={option}>{option || 'Todos'}</option>)}</select></label>;
